CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=1 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=1 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=2 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=2 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=3 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=3 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=4 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=4 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=5 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=5 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=6 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=6 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=7 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=7 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=8 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=8 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=9 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=9 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=10 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=10 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=11 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=11 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=12 runtime.model.num_layers=2 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
CUDA_DEVICE_MAX_CONNECTIONS=1  torchrun --nnodes 1 --nproc_per_node 1 train_dist.py  scripts/train_dist.yaml runtime.train.global_batch_size=12 runtime.model.num_layers=4 runtime.train.seq_length=2048 runtime.parallel.pp_deg=1 runtime.parallel.global_tp_deg=1 runtime.parallel.global_cp_deg=1 runtime.parallel.global_checkpoint=0 runtime.parallel.vocab_tp=1 runtime.parallel.vocab_cp=1 runtime.parallel.default_dp_type=ddp runtime.parallel.pipeline_type=gpipe runtime.parallel.mixed_precision=bf16 runtime.train.chunks=1 runtime.train.use_flash_attn=True runtime.train.sequence_parallel=True runtime.profile.profile=1 runtime.profile.profile_mode=batch runtime.profile.profile_unit=all runtime.profile.profile_forward=1 runtime.model.model_size=llama2-7b runtime.model.is_moe_model=False runtime.model.model_config_path=../model_configs/llama2-7b.yaml runtime.model.set_layernum_manually=1 runtime.model.set_seqlen_manually=1  2>&1 | tee profile.log
sleep 1
